name: testtable
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - python>=3.10,<3.12
    - sourmash>=4.8.11,<5
    - polars
    - pip
    - pytest
    - build
    - twine
    - make
    - pip:
        - sourmash_utils
